name = "MinimumVolumeEllipsoids"
uuid = "369a3862-bec2-4fd2-abcd-2df79a05ee65"
authors = ["Jasper Behrensdorf <behrensdorf@irz.uni-hannover.de>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "0.25"
PDMats = "0.11"
julia = "1"
